name: production_entry
description: Production Entry App

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter



  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.3
  dio: ^4.0.0
  shared_preferences: ^2.0.6
  flutter_staggered_animations: ^1.0.0
  flutter_vector_icons: ^1.0.0
  flutter_spinkit: ^5.0.0
  basic_utils: ^3.1.0
  async:
  qr_flutter: ^4.0.0
  flutter_svg: ^0.22.0
  native_widgets:
  another_flushbar: ^1.10.23
  #Device && info
  device_info: ^2.0.2
  #android_device_info: ^1.0.0
  imei_plugin: 1.2.0
  package_info: ^2.0.2
  geolocator: ^7.0.3
  provider: ^5.0.0
  intl: ^0.17.0
  flutter_barcode_scanner: ^2.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons:
  flutter_native_splash:

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/szl-logo.png"
  adaptive_icon_background: "#fff"
  adaptive_icon_foreground: "images/szl-logo.png"

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - images/
